### ISSUE TITLE
Transfer project board to this repo

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/papyrus#3]
@BLFiedler started a project board for this repo. We looked into transferring it here but didn't see a way quickly. @BLFiedler can you take a look? 

https://github.com/orgs/phetsims/projects/64/views/1

**Comment by BLFiedler** [comment]
Linked the board. Just need to convert relevant issues and delete any duplicates.

**Comment by BLFiedler** [comment]
Converted relevant and not already complete drafts on board to issues. Currently lack sufficient details and assignments.

**Comment by BLFiedler** [comment]
Calling this complete as we prioritize and create most relevant issues.
