### ISSUE TITLE
Create optional program info on the Board

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/papyrus#44]
This has come up a few times in design meetings. It would be nice to draw some information about detected programs right in the board view. Displaying similar info to the current projector view. Probably conditionally and only displayed when a checkbox is checked. Debugging info would include a rectangle around the program and possibly the program number or title.

**Comment by jbphet** [comment]
@BLFiedler - What would you say is the priority of this?  My recollection was that we talked quite a bit at a recent design meeting about merging the two views (projector and board) and making it possible to enable either or both, but ultimately decided not to spend time on it just yet.  True?

**Comment by BLFiedler** [comment]
Let's hold on prioritizing this just yet. There are likely to be more pressing interface needs. 

I believe folks could just have a model program draw a simple rectangle with XY coordinates that track the paper position and draw the title? Might be useful to add to a few for demo purposes before we hardcode something.

**Comment by BLFiedler** [comment]
We're not going to pull the full functionality of Projector over any time soon. Closing.
