### ISSUE TITLE
Add the ability to create new paper programs from existing examples & templates

### ISSUE THREAD

**Issue by jbphet** [phetsims/papyrus#47]
In #46 we are adding a number of examples and templates that we want the users to use as the basis for creating new paper programs.  We will need to add the ability to copy these into new programs to support this use case.

**Comment by jessegreenberg** [comment]
While working with @terracoda today we noticed that you cannot create a copy from one space into another yet. We think the display is showing all programs but when you try to create a new one it is looking for that program in the current space.

**Comment by jessegreenberg** [comment]
Fixed with the above commit.

**Comment by jessegreenberg** [comment]
@BLFiedler what are the next steps for this issue, or can it be closed?

**Comment by BLFiedler** [comment]
This is complete! Any additional interface arrangments should be their own issue.
