### ISSUE TITLE
Set up a shared DB for storing the scripts

### ISSUE THREAD

**Issue by jbphet** [phetsims/papyrus#5]
The paper programming environment uses a database for storing the scripts associated with each piece of paper.  In our early prototyping, we've had each user set up a local instance of PostgreSQL.  It would be good to migrate to a shared DB that is accessible from anywhere, but is also secure so that malicious actors can't mess it up.

@mattpen - You've got the most experience with SQL databases on the PhET team.  How would you recommend starting to approach this?

**Comment by mattpen** [comment]
@jbphet - Can you provide some more context?  I'm not familiar with the paper programming environment at all.  Is it making SQL calls directly, or do we need some kind of HTTP/REST layer to control access and validate input?

The only remote access we have setup at phet is a MySQL database on phet-server2.  There is a php script that writes to it locally in response to HTTP requests, and yotta reads from it remotely on bayes. I didn't set this up, but I was able to recreate it when we migrated from phet-server to phet-server2.  So I wouldn't consider myself an expert in distributed database services, but I could probably help.

I would say that if we are opening ports to allow SQL calls from anywhere on the internet directly to the database, we will want to make sure that this is strongly encapsulated from our production website database, hopefully on a different machine entirely.  I'm not sure which machine would be appropriate.  Will this be a production level system, or it is just for research or testing (or something else)?

**Comment by BLFiedler** [comment]
Let's go ahead and investigate free or paid services to temporarily host something outside of the university servers, at least while we explore. We can move things later as long as we don't lose the database itself :)

**Comment by jessegreenberg** [comment]
We looked into this a bit today and found the knexfile.js (https://github.com/phetsims/papyrus/blob/d409fc80ee7c1924d8e95af56b7dfbf838b8a5c0/knexfile.js#L17-L16) where we can change the URL for the database. We tested by adding a .env file to the root of the project with a different URL at DATABASE_URL, and saw the project try to use it..

**Comment by BLFiedler** [comment]
We discovered in design meeting that several of us needed to re-select the space name "shared-experiments" in order to get the programs to show up in the queue/editor.

- [ ] Fix this! :)

**Comment by BLFiedler** [comment]
We have the green light to buy the "Pretty Panda" tier on ElephantSQL. Need to check with Oliver on details of the purchase.

**Comment by jbphet** [comment]
As of this moment, we have set up the ability for the server to connect to a DB hosted by ElephantSQL, and are using the free "Tiny Turtle" plan.  The details of the DB name and how to connect to it will be kept out of GitHub as a security measure.

**Comment by jbphet** [comment]
The plan for the ElephantSQL DB has been upgraded to Pretty Panda, and we should now be able to support up to 20 concurrent connections.  I also just sent @jessegreenberg and @BLFiedler invitations to the team admin privileges.  I think the basics of this issue are now covered, so I'll unassign myself.

@jessegreenberg and @BLFiedler - Please let me know if you don't get the invitations or have any issues with getting access to the DB.

**Comment by jessegreenberg** [comment]
Thanks! I received the invitation and have access.

**Comment by BLFiedler** [comment]
DONE
