### ISSUE TITLE
Investigate flexibility of tool with phetlib integration at the script level

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/papyrus#7]
Discussed during meeting,

We would like to bias the flexibility of the tool in using our existing PhET libraries without embedding new functionality or abstraction into the tool code. Yes, this will make the scripts more complex, but less development will be needed on the tool side and more focus on the script side (which can involve everyone). We hope to generate enough example scripts that 1.) there's something to lean on to create new scripts and 2.) there are sufficient examples to modify on the fly, or even 3.) enough examples exist that someone might just "plug n play" from existing scripts.

I'm pairing that idea with our need to communicate values, variables, etc between scripts (e.g., a model environment script gets the mass value from another script).

Assigning JG and JB to flesh out details, questions, and needs.

**Comment by jessegreenberg** [comment]
I looked into getting a reference to the model directly in the paper program like this:
In program code:
```js
  // NOTE: One strategy that I believe we could get working by copying some projector code into board
  const modelProperty = await paper.get( 'model' );
  console.log( modelProperty );

  modelProperty.link( modelProperty => {
    if ( modelProperty.altitudeProperty ) {
      modelProperty.altitudeProperty.link( altitude => {
        console.log( altitude );
      } );
    }
  } );
``` 

And adding a way to get the actual modelProperty from papyrus - in Program.js:
```js
      else if ( sendData.name === 'model' ) {

        // TODO: I hoped that you could possibly reference the model over here, but that is not possible. This method
        // TODO: Could maybe be moved to Board.js though!
        console.log( this._program().number.toString() );
        this._worker.postMessage( {
          messageId,
          receiveData: { object: this._program().number.toString() },
        } );
      }
```

As noted by the TODOs, this might work but we would need this code to be run from Board (instead of Projector) so we have access to the modelProperty.

But we decided not to continue with this because it makes it harder to use phet-lib. We prefer writing javascript functions in programs that can be evaluated from Board in papyrus.

**Comment by BLFiedler** [comment]
@jbphet @jessegreenberg Any notes you want to add about our integration of phetlib you want to make here before closing?

**Comment by jbphet** [comment]
> Any notes you want to add about our integration of phetlib you want to make here before closing?

Here is a summary of how we are supporting the use of phetlib from Paper Programs at this point in time:

- There is a "Simulation Design Board" that exists where the PhET code is interpreted and run.  It extracts code and data from the local storage and uses it to place UI and other view components on the board and set up relationships between them.
- On the Paper Programs side, there are three handlers that can be defined which can access PhET code.  The are `onProgramAdded`, `onProgramChangedPosition`, and `onProgramRemoved`.  The names are fairly self explanatory.  And example program will be pasted below.
- So far, this seems to work reasonably well for a lot of things.  However, it does have some downsides.  One is that the code being defined on the Paper Program side and then being sent as a string to the board has only local scoping, so no common code can be shared between the different handlers.  This is unusual, and is likely to be confusing to users.

<details>

```js
// Altitude Image

// Add an image to the sim where it's vertical position is linked to a Property that sets the altitude.

importScripts('paper.js');

(async () => {

  const onProgramAdded = ( paperProgramNumber, scratchpad, sharedData ) => {

    // const imageSource = 'girlInAir.png';
    // const imageSource = 'lunarLander.png';
    const imageSource = 'birdInAir.png';

    // Create a Scenery image node.
    const imageElement = document.createElement( 'img' );
    imageElement.setAttribute( 'src', `media/images/${imageSource}` );
    const imageNode = new scenery.Image( imageElement, {
      maxWidth: 100
    } );

    // Add to the view
    sharedData.scene.addChild( imageNode );

    // Assign to the scratchpad so that we can move it and remove it later
    scratchpad.imageNode = imageNode;

    // Adjust the position of the image as the altitude property changes.
    const model = sharedData.modelProperty.value;
    if ( model.altitudeProperty ) {

      // Assign to the scratchpad so we can unlink when the program is removed
      scratchpad.altitudeListener = altitude => {
        const viewAltitude =  sharedData.displaySize.height * ( 1 - altitude / 10 );
        imageNode.centerY = viewAltitude;
      };
      model.altitudeProperty.link( scratchpad.altitudeListener );
    }
    else {
      alert( 'No altitudeProperty in model, add that program first' );
    }
  };
 
  // Called when the program is removed.
  const onProgramRemoved = ( paperProgramNumber, scratchpad, sharedData ) => {
    console.log( `onProgramRemoved called for ppn ${paperProgramNumber}`);
    const model = sharedData.modelProperty.value;

    // Remove the image from the view
    if ( scratchpad.imageNode ){
      sharedData.scene.removeChild( scratchpad.imageNode );
      scratchpad.imageNode = null;
    }
    else {
      alert( 'Error: imageNode node not found in scratchpad data.' );
    }

    // Remove the listener that moves the image with the model
    if ( model.altitudeProperty && scratchpad.altitudeListener ) {
      model.altitudeProperty.unlink( scratchpad.altitudeListener );
      scratchpad.altitudeListener = null;
    }
    else {
      alert( 'altitudeProperty and altitudeListener missing during removal' );
    }
  };

  // Add the state change handler defined above as data for this paper.
  await paper.set('data', {
    paperPlaygroundData: {
      updateTime: Date.now(),
      eventHandlers: {
        onProgramAdded: onProgramAdded.toString(),
        onProgramRemoved: onProgramRemoved.toString()
      }
    }
  } );

    // Get a canvas object for this paper.
  const canvas = await paper.get('canvas');

  // Write a message on the Canvas.
  const ctx = canvas.getContext('2d');
  ctx.font = '20px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillStyle = 'rgb(155,25,34)';
  ctx.fillText('Image at', canvas.width / 2, canvas.height / 2 - 10);
  ctx.fillStyle = 'rgb(155,25,34)';
  ctx.fillText('Altitude', canvas.width / 2, canvas.height / 2 + 20);
})();

```
</details>

**Comment by jbphet** [comment]
Notes added above.  I think we can close this, and use more specific issues for the next steps.
